services:
  app:
    ports: !reset []
    networks:
      default: {}
      web:
        aliases:
          - f1-app
      db: {}
  caddy:
    profiles: !override
      - legacy-edge
    networks:
      default: {}
      web: {}

networks:
  web:
    external: true
    name: mhv-web
  db:
    external: true
    name: mhv-db
