services:
  app:
    ports: !reset []
    networks:
      default: {}
      web:
        aliases:
          - f1-app
  caddy:
    profiles: !override
      - legacy-edge
    networks:
      default: {}
      web: {}

networks:
  web:
    external: true
    name: wok-web
